defaults:
  - _self_
  - model: llama
dry_run: False
wandb:
  project: "hpc_t5_superglue"
  name: null
  entity: "yuanhezhang6-university-of-warwick"
hydra:
  sweeper:
    params:
      ++dataset_name: meta_math # codefeedback #  meta_math #  wizard_lm
      ++seed: 42
