name: openai/clip-vit-base-patch32
type: clip
epochs: 1
per_device_batch_size: 1
real_batch_size: 32
bf16: True
eval_epochs: 1
early_stopping_patience: 3
logging_steps: 1
learning_rate: 2e-5
weight_decay: 0.0
prec_reg: 1e-6